import { NextRequest, NextResponse } from 'next/server';
import { getServiceRoleClient } from '@/lib/supabase-admin';

// GET /api/roles/[id]/permissions - Get all permissions for a role
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const supabase = getServiceRoleClient();

    const { data: permissions, error } = await supabase
      .from('role_permissions')
      .select(`
        *,
        sub_modules!inner(
          id,
          sub_module_name,
          sub_module_key,
          route_path,
          modules!inner(
            id,
            module_name,
            module_key
          )
        ),
        permission_categories!inner(
          id,
          category_name,
          category_key,
          category_type
        )
      `)
      .eq('role_id', id)
      .order('created_at', { ascending: true });

    if (error) {
      console.error('Error fetching role permissions:', error);
      return NextResponse.json(
        { error: 'Failed to fetch permissions', details: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json({ data: permissions }, { status: 200 });
  } catch (error) {
    console.error('Error in GET /api/roles/[id]/permissions:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

// POST /api/roles/[id]/permissions - Set permissions for a role
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    
    // Validate request body
    let body;
    try {
      body = await request.json();
    } catch (parseError) {
      console.error('Error parsing request body:', parseError);
      return NextResponse.json(
        { 
          error: 'Invalid request body', 
          details: 'Request body must be valid JSON',
          code: 'INVALID_JSON'
        },
        { status: 400 }
      );
    }
    
    const { permissions } = body;

    if (!Array.isArray(permissions)) {
      return NextResponse.json(
        { error: 'permissions must be an array' },
        { status: 400 }
      );
    }

    const supabase = getServiceRoleClient();

    // Verify role exists
    const { data: role, error: roleError } = await supabase
      .from('roles')
      .select('id')
      .eq('id', id)
      .single();

    if (roleError || !role) {
      return NextResponse.json(
        { error: 'Role not found' },
        { status: 404 }
      );
    }

    // Prepare permission records
    // Note: The database may have a permission_id column that requires a value
    // If permission_id exists and is NOT NULL, the database should auto-generate it
    // If it doesn't auto-generate, we'll let Supabase handle it or the migration script will fix it
    const permissionRecords = permissions.map((perm: {
      sub_module_id: string;
      category_id: string;
      view_access: boolean;
      edit_access: boolean;
    }) => ({
      role_id: id,
      sub_module_id: perm.sub_module_id,
      category_id: perm.category_id,
      view_access: perm.view_access || false,
      edit_access: perm.edit_access || false,
      // Note: permission_id should be auto-generated by database if column exists
      // If error persists, run fix_role_permissions_schema.sql migration
    }));

    // Delete existing permissions for this role
    const { error: deleteError } = await supabase
      .from('role_permissions')
      .delete()
      .eq('role_id', id);

    if (deleteError) {
      console.error('Error deleting existing permissions:', deleteError);
      return NextResponse.json(
        { error: 'Failed to update permissions', details: deleteError.message },
        { status: 500 }
      );
    }

    // Insert new permissions
    if (permissionRecords.length > 0) {
      // Validate all foreign keys exist before inserting
      const subModuleIds = [...new Set(permissionRecords.map(p => p.sub_module_id))];
      const categoryIds = [...new Set(permissionRecords.map(p => p.category_id))];

      // Check if all sub_modules exist
      const { data: existingSubModules, error: subModuleError } = await supabase
        .from('sub_modules')
        .select('id')
        .in('id', subModuleIds);

      if (subModuleError) {
        console.error('Error checking sub_modules:', subModuleError);
        return NextResponse.json(
          { error: 'Failed to validate sub-modules', details: subModuleError.message },
          { status: 500 }
        );
      }

      const existingSubModuleIds = new Set(existingSubModules?.map(sm => sm.id) || []);
      const missingSubModules = subModuleIds.filter(id => !existingSubModuleIds.has(id));
      if (missingSubModules.length > 0) {
        return NextResponse.json(
          { error: 'Invalid sub-module IDs', details: `Missing sub-modules: ${missingSubModules.join(', ')}` },
          { status: 400 }
        );
      }

      // Check if all categories exist
      const { data: existingCategories, error: categoryError } = await supabase
        .from('permission_categories')
        .select('id')
        .in('id', categoryIds);

      if (categoryError) {
        console.error('Error checking permission_categories:', categoryError);
        return NextResponse.json(
          { error: 'Failed to validate permission categories', details: categoryError.message },
          { status: 500 }
        );
      }

      const existingCategoryIds = new Set(existingCategories?.map(c => c.id) || []);
      const missingCategories = categoryIds.filter(id => !existingCategoryIds.has(id));
      if (missingCategories.length > 0) {
        return NextResponse.json(
          { error: 'Invalid category IDs', details: `Missing categories: ${missingCategories.join(', ')}` },
          { status: 400 }
        );
      }

      // Remove duplicates based on unique constraint
      const uniqueRecords = permissionRecords.reduce((acc, record) => {
        const key = `${record.role_id}-${record.sub_module_id}-${record.category_id}`;
        if (!acc.has(key)) {
          acc.set(key, record);
        }
        return acc;
      }, new Map());

      const deduplicatedRecords = Array.from(uniqueRecords.values());

      // Batch inserts for large permission sets to avoid timeout
      const BATCH_SIZE = 100;
      const allInsertedPermissions: Record<string, unknown>[] = [];
      
      for (let i = 0; i < deduplicatedRecords.length; i += BATCH_SIZE) {
        const batch = deduplicatedRecords.slice(i, i + BATCH_SIZE);
        const { data: batchPermissions, error: insertError } = await supabase
          .from('role_permissions')
          .insert(batch)
          .select();

        if (insertError) {
          console.error('Error inserting permissions batch:', insertError);
          console.error('Batch records:', JSON.stringify(batch, null, 2));
          
          // Handle specific database errors
          if (insertError.message?.includes('timeout') || insertError.message?.includes('fetch failed')) {
            return NextResponse.json(
              { 
                error: 'Database connection timeout', 
                details: 'The request took too long to complete. Please try again.',
                code: 'DB_TIMEOUT'
              },
              { status: 504 }
            );
          }
          
          // Handle unique constraint violations
          if (insertError.code === '23505' || insertError.message?.includes('unique')) {
            return NextResponse.json(
              { 
                error: 'Duplicate permission', 
                details: 'This permission already exists for this role.',
                code: 'DUPLICATE_PERMISSION'
              },
              { status: 409 }
            );
          }
          
          // Handle foreign key violations
          if (insertError.code === '23503' || insertError.message?.includes('foreign key')) {
            return NextResponse.json(
              { 
                error: 'Invalid reference', 
                details: 'One or more referenced records do not exist.',
                code: 'FOREIGN_KEY_VIOLATION'
              },
              { status: 400 }
            );
          }
          
          // Handle NOT NULL constraint violations (e.g., permission_id)
          if (insertError.code === '23502' || insertError.message?.includes('null value') || insertError.message?.includes('not-null constraint')) {
            return NextResponse.json(
              { 
                error: 'Database schema mismatch', 
                details: 'The role_permissions table has a permission_id column that requires a value. Please run the fix_role_permissions_schema.sql migration script to fix this issue.',
                code: 'NOT_NULL_VIOLATION',
                hint: 'Run the SQL migration: fix_role_permissions_schema.sql'
              },
              { status: 500 }
            );
          }
          
          return NextResponse.json(
            { error: 'Failed to save permissions', details: insertError.message, code: insertError.code },
            { status: 500 }
          );
        }
        
        if (batchPermissions) {
          allInsertedPermissions.push(...batchPermissions);
        }
      }

      return NextResponse.json(
        { data: allInsertedPermissions, message: 'Permissions updated successfully' },
        { status: 200 }
      );
    }

    return NextResponse.json(
      { message: 'All permissions removed successfully' },
      { status: 200 }
    );
  } catch (error) {
    console.error('Error in POST /api/roles/[id]/permissions:', error);
    console.error('Error details:', {
      message: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
      name: error instanceof Error ? error.name : undefined,
      error: JSON.stringify(error, Object.getOwnPropertyNames(error))
    });
    
    // Handle timeout and connection errors specifically
    if (error instanceof Error) {
      if (error.message.includes('timeout') || error.message.includes('Timeout') || 
          error.message.includes('fetch failed') || error.message.includes('ConnectTimeoutError')) {
        return NextResponse.json(
          { 
            error: 'Connection timeout', 
            details: 'Unable to connect to the database. Please check your internet connection and try again.',
            code: 'CONNECTION_TIMEOUT'
          },
          { status: 504 }
        );
      }
      
      if (error.message.includes('network') || error.message.includes('Network')) {
        return NextResponse.json(
          { 
            error: 'Network error', 
            details: 'Network connection failed. Please check your internet connection and try again.',
            code: 'NETWORK_ERROR'
          },
          { status: 503 }
        );
      }
      
      // Return error with message
      return NextResponse.json(
        { 
          error: 'Internal server error',
          details: error.message || 'An unexpected error occurred',
          code: 'INTERNAL_ERROR'
        },
        { status: 500 }
      );
    }
    
    // Fallback for non-Error objects
    return NextResponse.json(
      { 
        error: 'Internal server error',
        details: 'An unexpected error occurred',
        code: 'UNKNOWN_ERROR'
      },
      { status: 500 }
    );
  }
}
